pass_min: 6
name_max: 50
email_max: 255
size_gravatar: 80
size_gravatar_user: 50
check_remember: 1
users_per_page: 20
expired_time: 2
max_content: 140
pic_size: 5
resize_to_limit: 400
megabytes: 1024
gravatar_size_of_follow: 30
